// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6133.Steamworks;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon drivetrainLeftMotor1;
    public static CANTalon drivetrainLeftMotor2;
    public static CANTalon drivetrainLeftMotor3;
    public static CANTalon drivetrainRightMotor1;
    public static CANTalon drivetrainRightMotor2;
    public static CANTalon drivetrainRightMotor3;
    public static RobotDrive drivetrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SendableChooser allianceChooser;
    public static SendableChooser liftChooser;
    public static SendableChooser shootChooser;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainLeftMotor1 = new CANTalon(1);
        drivetrainLeftMotor2 = new CANTalon(3);
        drivetrainLeftMotor3 = new CANTalon(5);
        
        drivetrainRightMotor1 = new CANTalon(2);
        drivetrainRightMotor2 = new CANTalon(4);
        drivetrainRightMotor3 = new CANTalon(6);

        drivetrainRobotDrive = new RobotDrive(drivetrainLeftMotor1, drivetrainRightMotor1);
        
        drivetrainRobotDrive.setSafetyEnabled(true);
        drivetrainRobotDrive.setExpiration(0.1);
        drivetrainRobotDrive.setSensitivity(0.5);
        drivetrainRobotDrive.setMaxOutput(1.0);

        drivetrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        drivetrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        allianceChooser = new SendableChooser();
        allianceChooser.addDefault("Blue Alliance", "blue");
        allianceChooser.addObject("Red Alliance", "red");
        SmartDashboard.putData("Alliance Color", allianceChooser);
        
        liftChooser = new SendableChooser();
        liftChooser.addDefault("Lift 2 - Middle", "mid");
        liftChooser.addObject("Lift 1 - Left", "left");
        liftChooser.addObject("Lift 3 - Right", "right");
        SmartDashboard.putData("Lift Chooser", liftChooser);
        
        shootChooser = new SendableChooser();
        shootChooser.addDefault("Do not shoot", "ceaseFire");
        shootChooser.addObject("FIRE ZE MISSILES!", "fire");
        shootChooser.addObject("Aim, no fire", "aim");
        SmartDashboard.putData("Launcher Settings", shootChooser);
    }
}
